site_name: Emart

theme:
  name: material
plugins:
  - search
  - print-site:
      add_table_of_contents: true
      toc_title: 'Table of Contents'
      toc_depth: 6
      add_cover_page: true
      cover_page_template: "docs/assets/templates/custom_cover_page.tpl"